transcriptome_selections:
    - /vortexfs1/omics/alexander/data/mmetsp/MMETSP0321_clean.fasta
    - /vortexfs1/omics/alexander/data/mmetsp/MMETSP0369_clean.fasta
    - /vortexfs1/omics/alexander/data/mmetsp/MMETSP0397_clean.fasta
    - /vortexfs1/omics/alexander/data/mmetsp/MMETSP0469_clean.fasta
    - /vortexfs1/omics/alexander/data/mmetsp/MMETSP0800_clean.fasta
    - /vortexfs1/omics/alexander/data/mmetsp/MMETSP0884_clean.fasta
    - /vortexfs1/omics/alexander/data/mmetsp/MMETSP0896_clean.fasta
    - /vortexfs1/omics/alexander/data/mmetsp/MMETSP0975_clean.fasta
    - /vortexfs1/omics/alexander/data/mmetsp/MMETSP1117_clean.fasta
    - /vortexfs1/omics/alexander/data/mmetsp/MMETSP1338_clean.fasta
    - /vortexfs1/omics/alexander/data/mmetsp/MMETSP1349_clean.fasta
    - /vortexfs1/omics/alexander/data/mmetsp/MMETSP1411_clean.fasta
protein_files:
    - /vortexfs1/omics/alexander/data/mmetsp/MMETSP0321_clean.pep.fa
    - /vortexfs1/omics/alexander/data/mmetsp/MMETSP0369_clean.pep.fa
    - /vortexfs1/omics/alexander/data/mmetsp/MMETSP0397_clean.pep.fa
    - /vortexfs1/omics/alexander/data/mmetsp/MMETSP0469_clean.pep.fa
    - /vortexfs1/omics/alexander/data/mmetsp/MMETSP0800_clean.pep.fa
    - /vortexfs1/omics/alexander/data/mmetsp/MMETSP0884_clean.pep.fa
    - /vortexfs1/omics/alexander/data/mmetsp/MMETSP0896_clean.pep.fa
    - /vortexfs1/omics/alexander/data/mmetsp/MMETSP0975_clean.pep.fa
    - /vortexfs1/omics/alexander/data/mmetsp/MMETSP1117_clean.pep.fa
    - /vortexfs1/omics/alexander/data/mmetsp/MMETSP1338_clean.pep.fa
    - /vortexfs1/omics/alexander/data/mmetsp/MMETSP1349_clean.pep.fa
    - /vortexfs1/omics/alexander/data/mmetsp/MMETSP1411_clean.pep.fa
community_spec: files/default_communities.csv
outputdir: ../eukrhythmic_paper_trials_September21/jEUKebox-Trial2-CommB
total_size: 100000
community_configs:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
community_1_transcriptome: 1
